apiVersion: v1
kind: Pod
metadata:
  name: devkonnect-be
spec:
  containers:
    - name: devkonnect-be
      image: freeman82/dev-konnect:41
      ports:
        - containerPort: 5000
      env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: be-devkonnect
              key: DATABASE_URI
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: be-devkonnect
              key: ACCESS_TOKEN_SECRET
        - name: REFRESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: be-devkonnect
              key: REFRESS_TOKEN_SECRET
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: be-devkonnect
              key: CLOUDINARY_CLOUD_NAME
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: be-devkonnect
              key: CLOUDINARY_API_KEY
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: be-devkonnect
              key: CLOUDINARY_API_SECRET
        - name: CLOUDINARY_DEFAULT_URL
          valueFrom:
            secretKeyRef:
              name: be-devkonnect
              key: CLOUDINARY_DEFAULT_URL
        - name: CLOUDINARY_DEFAULT_PUBLIC_ID
          valueFrom:
            secretKeyRef:
              name: be-devkonnect
              key: CLOUDINARY_DEFAULT_PUBLIC_ID

  imagePullSecrets:
    - name: dockerhub-creds
